#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e

# job control?
set -m


cd "$ROOT_DIR"


# start as background process
DEFAULT_TO_PORT9000='--port 9000'
instrument-server $DEFAULT_TO_PORT9000 "$@" command_plugin_example.yaml &
